### ISSUE TITLE
Add nostr-fetch and nosdump to awesome-nostr

### ISSUE THREAD

**Issue by atrifat** [jiftechnify/nostr-fetch#113]
Actually, this is not really issue report. I hope you don't mind to be included in awesome-nostr repo (aljazceru/awesome-nostr#349). I think nostr-fetch and nosdump should be presented in awesome-nostr repo.

Thank you for your works jiftechnify-san :)

**Comment by jiftechnify** [comment]
Thank you for introducing my works!  I appreciate it.

I'm glad that they help your works :)
