### ISSUE TITLE
Infinite error loop on fetchLatestEventsPerAuthor

### ISSUE THREAD

**Issue by SnowCait** [jiftechnify/nostr-fetch#239]
`fetchLatestEventsPerAuthor` sometimes repeats to reconnect to relay and gets "WebSocket error".
Then its iterator doesn't complete.
The frequency of occurrence seems to increase in proportion to the number of authors.

Log (Deno):
https://github.com/SnowCait/nostr-japanese-users/actions/runs/8283670090/job/22667396273#step:5:144

Reproduction code (Browser):
https://github.com/SnowCait/svelte-sandbox/blob/92078b270e50cd5f9d3dad3b4eff3b7f382ea172/nostr-fetch/src/routes/%2Bpage.svelte

After reconnect, no REQs are published.
![image](https://github.com/jiftechnify/nostr-fetch/assets/1297512/be0fdd21-fb5f-4271-8fbe-15e7d2d7315d)

I don't know if it's related, last REQ received no data.
![image](https://github.com/jiftechnify/nostr-fetch/assets/1297512/87f0aab4-1d63-47b6-af64-14b6213af262)

**Comment by jiftechnify** [comment]
The root cause of this issue was never ending `fetchLatestEventsPerAuthor` if `authors` array have duplicated pubkey. It should be fixed by #241.
